### ISSUE TITLE
一卡通的事情是真的吗😮

### ISSUE THREAD

**Issue by FrezCirno** [skyleaworlder/skyleaworlder.github.io#29]
震惊.jpg
膜拜大佬.jpg

**Comment by skyleaworlder** [comment]
哈哈哈哈关于一卡通同步这件事，是我们老师当时上课随口说的。也许是真的，也许是我们老师 为了创设一个思考环境 自己杜撰出来的。（但我的 数据结构老师 和 安全体系结构 老师都提过这件事，我觉得这件事偏真）

当然，现在咱们学校肯定是没有一卡通同步问题了233，如果这个问题曾经是真正存在的，那么只能说明一件事：“技术解决不了所有的问题”。

至少对于以前是这样；对于现在，还是这样。

**Comment by skyleaworlder** [comment]
（刚刚后顾了下我都写了些什么
实际上那篇博客缝合了很多东西……实际上 x 通动力系统 和 一卡通 无关，不限期关闭 J 区一卡通在 S 区的使用权限是子虚乌有的 balabala

**Comment by FrezCirno** [comment]
似乎明白了
